subsystems:
    # Alignment:
    # AnalysisAlgos:
    # AnalysisDataFormats:
    # BigProducts:
    # CalibCalorimetry:
    CalibFormats:
        whitelist:
          - CaloObjects
          - CastorObjects
    # CalibMuon:
    # CalibPPS:
    # CalibTracker:
    # Calibration:
    # CalibOnlineTools:
    CommonTools:
        whitelist:
          - Egamma
          - UtilAlgos
          - Utils
    CondCore:
        whitelist:
          - CondDB
          - DBOutputService
          - PluginSystem
    CondFormats:
        whitelist:
          - Alignment
          - AlignmentRecord
          - CastorObjects
          - CSCObjects
          - Common
          - DataRecord
          - EgammaObjects
          - External
          - HIObjects
          - L1TObjects
          - PhysicsToolsObjects
          - RPCObjects
          - RunInfo
          - Serialization
    # CondTools:
    # Configuration:
    # DPGAnalysis:
    # DQM:
    # DQMOffline:
    # DQMServices:
    DataFormats:
    # DetectorDescription:
    # DiffractiveForwardAnalysis:
    # Documentation:
    # EgammaAnalysis:
    # ElectroWeakAnalysis:
    # EventFilter:
    FWCore:
    # FastSimDataFormats:
    # FastSimulation:
    # Fireworks:
    # GeneratorInterface:
    Geometry:
        whitelist:
          - CaloGeometry
          - CommonDetUnit
          - CommonTopologies
          - Records
    # GeometryReaders
    # HLTrigger:
    # HLTriggerOffline:
    # HeavyFlavorAnalysis:
    # HeterogeneousCore:
    # HiggsAnalysis:
    # IOMC:
    IOPool:
    IORawData:
        whitelist:
          - DTCommissioning
    IgTools:
    # JetMETAnalysis:
    # JetMETCorrections:
    # L1Trigger:
    # L1TriggerConfig:
    L1TriggerOffline:
    # MagneticField:
    Mixing:
    # MuonAnalysis:
    # OnlineDB:
    # PerfTools:
    PhysicsTools:
        whitelist:
          - SelectorUtils
          - Utilities
    # QCDAnalysis:
    # RecoBTag:
    # RecoBTau:
    # RecoCTPPS:
    RecoCaloTools:
    # RecoEcal:
    RecoEgamma:
        whitelist:
          - EgammaMCTools
    # RecoHGCal:
    # RecoHI:
    # RecoJets:
    # RecoLocalCalo:
    # RecoLocalFastTime:
    # RecoLocalMuon:
    # RecoLocalTracker:
    # RecoLuminosity:
    # RecoMET:
    # RecoMTD:
    # RecoMuon:
    # RecoParticleFlow:
    # RecoPixelVertexing:
    # RecoRomanPot:
    # RecoTBCalo:
    # RecoTauTag:
    # RecoTracker:
    # RecoVertex:
    # SLHCUpgradeSimulations:
    # SUSYBSMAnalysis:
    # SimCalorimetry:
    SimDataFormats:
    # SimFastTiming:
    # SimG4CMS:
    # SimG4Core:
    # SimGeneral:
    # SimMuon:
    # SimPPS:
    # SimRomanPot:
    # SimTracker:
    TBDataFormats:
    # TauAnalysis:
    # TopQuarkAnalysis:
    # TrackPropagation:
    # TrackingTools:
    Utilities:
        blacklist:
          - DavixAdaptor
          - DCacheAdaptor
          - PPS
          - ReleaseScripts
          - StaticAnalyzers
    # Validation:

requirements-nolink:
  - boost_header
  - boost_python
  - clhepheader
  - vdt_headers
  - ofast-flag
  - sigcpp
  - roofit
  - eigen
  - gcc-atomic
  - xrootd
  - catch2
  - geant4core
  - stdcxx-fs

requirements-rename:
    libuuid: uuid
    md5: cms-md5
    clhep: CLHEP
    hepmc: HepMC
    heppdt: HepPDT
    xz: lzma
    openssl: crypto
    zlib: z
    tensorflow-cc: tensorflow_cc
    py2-pybind11: python2.7
    python: python2.7
    python3: python3

requirements-include-dir:
    py2-pybind11: /usr/include/python2.7
    boost_python: /usr/include/python2.7
    xrootd: /usr/include/xrootd
    XrdCl: /usr/include/xrootd
    catch2: /usr/include/catch2
    tensorflow-cc: /usr/include/tensorflow
    geant4: /usr/include/Geant4
    eigen: /usr/include/eigen3
    geant4core: /usr/include/Geant4

cmake-lists-root:
  - cmake_minimum_required(VERSION 3.2)
  - set(CMAKE_CXX_STANDARD 17)
  - project(CMSSW)
  - set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wno-attributes -msse3 -lrt")
  - add_subdirectory(cmssw)

build-test: False
build-bin: True
